name: flareline_uikit
description: A comprehensive Flutter UI kit with modern design components, forked and customized for dal_flutter_app compatibility.
version: 1.0.0
homepage: https://github.com/aelahmar/flare_line_ui_kit

environment:
  sdk: 3.8.1
  flutter: 3.32.1

dependencies:
  flutter:
    sdk: flutter

  # Core UI Dependencies Only
  flutter_svg: ^2.2.0
  intl: 0.20.2
  cupertino_icons: 1.0.8

  # Animation Libraries - for UI components
  animate_do: 4.2.0
  shimmer: 3.0.0
  lottie: 3.3.1

  # State Management - only if UI components need state
  flutter_bloc: 8.1.6
  equatable: 2.0.5
  rxdart: 0.28.0
  logger: 2.6.0
  get_storage: 2.1.1

  # Responsive Design - for UI kit components
  responsive_framework: 1.5.1
  responsive_builder: ^0.7.1

  # Essential UI Components Only
  auto_size_text: 3.0.0
  carousel_slider: 5.0.0
  flutter_colorpicker: 1.1.0
  file_picker: 10.1.2
  image_picker: 1.1.2
  pin_code_fields: 8.0.1
  dotted_line: 3.2.3
  font_awesome_flutter: 10.8.0
  timer_count_down: 2.2.2
  flip_card: 0.7.0
  flutter_rating_bar: 4.0.1
  bottom_sheet: 4.0.4
  avatar_glow: 3.0.1
  desktop_drop: 0.6.1
  window_location_href: 1.0.1+2

  # Syncfusion Widgets - for UI components
  syncfusion_flutter_charts: 27.2.3
  syncfusion_flutter_datagrid: 27.2.3
  syncfusion_flutter_calendar: 27.2.3
  syncfusion_flutter_maps: 27.2.3

  # Typography
  google_fonts: 6.2.1

  # Basic utilities
  collection: 1.19.1

dependency_overrides:
  intl: 0.20.2
  freezed_annotation: 3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 5.0.0